services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: |
      npm install
      apt-get update
      apt-get install -y chromium-browser
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
      - key: NODE_ENV
        value: production
